kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume
  namespace: local-pvc
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 